"""add_currency_support

Revision ID: 362aa60e787f
Revises: 001_initial
Create Date: 2025-10-31 15:23:17.214376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362aa60e787f'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create agency_settings table if it doesn't exist
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    
    if 'agency_settings' not in tables:
        op.create_table('agency_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('primary_currency', sa.String(), nullable=False),
        sa.Column('currency_symbol', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_agency_settings_id'), 'agency_settings', ['id'], unique=False)
    
    # Add currency columns if they don't exist
    costs_columns = [col['name'] for col in inspector.get_columns('costs_fixed')]
    if 'currency' not in costs_columns:
        op.add_column('costs_fixed', sa.Column('currency', sa.String(), nullable=False, server_default='USD'))
    
    team_columns = [col['name'] for col in inspector.get_columns('team_members')]
    if 'currency' not in team_columns:
        op.add_column('team_members', sa.Column('currency', sa.String(), nullable=False, server_default='USD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'currency')
    op.drop_column('costs_fixed', 'currency')
    op.drop_index(op.f('ix_agency_settings_id'), table_name='agency_settings')
    op.drop_table('agency_settings')
    # ### end Alembic commands ###

