"""
Standardized error codes for the application
These codes are language-agnostic and can be translated on the frontend
"""
from enum import Enum


class ErrorCode(str, Enum):
    """Standardized error codes"""
    
    # Authentication & Authorization
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNAUTHORIZED = "UNAUTHORIZED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    
    # Resources
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    RESOURCE_IN_USE = "RESOURCE_IN_USE"
    RESOURCE_DELETED = "RESOURCE_DELETED"
    
    # Validation
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_INPUT = "INVALID_INPUT"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    INVALID_FORMAT = "INVALID_FORMAT"
    
    # Business Logic
    OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED"
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED"
    INSUFFICIENT_CREDITS = "INSUFFICIENT_CREDITS"
    QUOTE_REQUIRED = "QUOTE_REQUIRED"
    
    # Organization & User
    ORG_NOT_FOUND = "ORG_NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    ORG_SWITCH_DENIED = "ORG_SWITCH_DENIED"
    
    # Project & Quote
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    QUOTE_NOT_FOUND = "QUOTE_NOT_FOUND"
    SERVICE_NOT_FOUND = "SERVICE_NOT_FOUND"
    TAX_NOT_FOUND = "TAX_NOT_FOUND"
    
    # External Services
    EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED"
    SMTP_CONFIGURATION_ERROR = "SMTP_CONFIGURATION_ERROR"
    PAYMENT_PROCESSING_ERROR = "PAYMENT_PROCESSING_ERROR"
    
    # System
    INTERNAL_ERROR = "INTERNAL_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    NETWORK_ERROR = "NETWORK_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

